#!/usr/bin/env bash
# Build the static board harness: frontend/_harness.html + frontend/_fixtures.js.
#
# Why this exists: a signed rebuild is ~20 minutes, and the board pages are
# plain JS against a tiny __TAURI__ surface — so we splice a fixture-backed
# stub in FRONT of board-shim.js (the shim bails out when __TAURI__ already
# exists) and drive the real board.html in any browser or in jsdom
# (scripts/harness-tests/). No Tauri, no MCP server, no login.
#
#   bash scripts/make_harness.sh
#   (cd frontend && python3 -m http.server 8899)
#   open http://localhost:8899/_harness.html?view=gamestats
#   variants:  &fixture=unauth   &fixture=coldboot
#
# Test hooks exposed on window:
#   __HARNESS_CALLS__      — every core.invoke {cmd, args}, in order
#   __HARNESS_LISTENERS__  — event name → [callbacks]; dispatch synthetic
#                            events with __HARNESS_EMIT__(name, payload)
#
# BOTH generated files are gitignored and MUST NOT exist when the app is
# built — they would ship in frontendDist.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=frontend/board.html
OUT=frontend/_harness.html
FIX=frontend/_fixtures.js

[ -f "$SRC" ] || { echo "missing $SRC (run from the repo)"; exit 1; }

# ── Fixtures ────────────────────────────────────────────────────────────────
cat > "$FIX" <<'EOF'
// Generated by scripts/make_harness.sh — do not commit, do not ship.
(function () {
  'use strict';
  var qs = location.search || '';
  var variant = (/[?&]fixture=([a-z]+)/.exec(qs) || [])[1] || 'default';

  function mkSeries(n) {
    var out = [];
    for (var i = 0; i < n; i++) {
      out.push({
        height: 4200000 + i,
        events: 20 + Math.round(18 * Math.abs(Math.sin(i / 9))),
        combat: (i % 13 === 0) ? 3 : 0,
        tx: 4 + (i % 7),
        raids: (i > n - 40) ? 2 : 1,
        structs: 5980 + Math.floor(i / 12),
        fuel: 9.1e12 + i * 3.1e8,
      });
    }
    return out;
  }
  function mkPlayers(metric) {
    var rows = [];
    for (var i = 1; i <= 25; i++) {
      rows.push({
        rank: i,
        player_id: '1-' + (100 + i),
        username: ['JPEG', 'Marklifer', 'Phoniffer', 'beezhan', 'Orbital'][i % 5] + '-' + i,
        pfp: null,
        // String-on-purpose: the Guild API sends numerics as strings and the
        // page must survive that end-to-end.
        pfp_attrs: '{"head":1,"neck":2,"body":1,"arms":0,"background":3}',
        guild_name: 'Guild ' + (1 + (i % 8)),
        tag: 'G' + (1 + (i % 8)),
        value: metric === 'alpha' ? (26 - i) * 1.7e9 : (metric === 'ore' ? (26 - i) * 137 : (26 - i) * 2.5e8),
      });
    }
    return rows;
  }
  var GUILDS = [];
  for (var g = 1; g <= 8; g++) {
    GUILDS.push({
      guild_id: '0-' + g,
      name: ['SN Corp', 'Oh Energy', 'Void Miners', 'Deep Anchor', 'Redline', 'Kessler', 'Farside', 'Nomad'][g - 1],
      logo: null,
      members: 900 - g * 97,
      alpha: String((9 - g) * 4.2e9),   // string numeric on purpose
      total_fuel: (9 - g) * 1.1e12,
      total_load: (9 - g) * 0.4e12,
      total_capacity: (9 - g) * 1.6e12,
      planets_complete: (9 - g) * 31,
    });
  }
  var SNAPSHOT = {
    auth_ok: true,
    block_height: 4200719,
    fast_updated_ms: Date.now() - 22000,
    heavy_updated_ms: Date.now() - 95000,
    sweeping: false,
    truncated: false,
    totals: {
      players: '2412',                 // string numeric on purpose
      guilds: 11,
      planets_total: 3120, planets_complete: 1893,
      structs_total: 6041, structs_destroyed: 812,
      fleets_total: 2380, fleets_away: 74,
      raids_active: 2, work_queue: 137,
      total_fuel: 9.13e12, total_load: 3.4e12, total_capacity: 1.28e13,
      total_alpha: 3.4e10, total_ore: 88410,
    },
    guilds: GUILDS,
    players_top: {
      alpha: mkPlayers('alpha'),
      ore: mkPlayers('ore'),
      structs_load: mkPlayers('structs_load'),
    },
    structs_by_type: [
      { type: 'mobile_artillery', count: 812, destroyed: 145 },
      { type: 'tank', count: 640, destroyed: 202 },
      { type: 'high_altitude_interceptor', count: 512, destroyed: 60 },
      { type: 'sam_launcher', count: 469, destroyed: 41 },
      { type: 'command_ship', count: 402, destroyed: 77 },
    ],
    structs_by_ambit: [
      { ambit: 'land', count: 2410 }, { ambit: 'air', count: 1620 },
      { ambit: 'water', count: 1102 }, { ambit: 'space', count: 909 },
    ],
    series: mkSeries(240),
  };
  if (variant === 'unauth') {
    SNAPSHOT = { auth_ok: false, block_height: 4200719, totals: {}, guilds: [], players_top: {}, series: [] };
  }
  if (variant === 'coldboot') {
    SNAPSHOT = { auth_ok: null, block_height: 0, fast_updated_ms: 0, heavy_updated_ms: 0,
      sweeping: true, truncated: false, totals: {}, guilds: [], players_top: {},
      structs_by_type: [], structs_by_ambit: [], series: [] };
  }

  var F = {
    mcp_game_stats_snapshot: SNAPSHOT,
    mcp_board_html: '<div class="sui-data-card-row">harness ops snapshot</div>',
    mcp_board_feed: [],
    mcp_health: { ok: true },
    mcp_grass_recent: [],
  };

  var calls = [];
  var listeners = {};
  window.__HARNESS_CALLS__ = calls;
  window.__HARNESS_LISTENERS__ = listeners;
  window.__HARNESS_EMIT__ = function (name, payload) {
    (listeners[name] || []).forEach(function (cb) { cb({ payload: payload }); });
  };
  window.__TAURI__ = {
    core: {
      invoke: function (cmd, args) {
        calls.push({ cmd: cmd, args: args });
        return Object.prototype.hasOwnProperty.call(F, cmd)
          ? Promise.resolve(F[cmd])
          : Promise.reject('harness: no fixture for ' + cmd);
      },
    },
    event: {
      listen: function (name, cb) {
        (listeners[name] = listeners[name] || []).push(cb);
        return Promise.resolve(function () {});
      },
    },
    window: { getCurrent: function () { return { label: 'harness' }; } },
  };
})();
EOF

# ── Harness page: fixture stub spliced ahead of board-shim.js ───────────────
python3 - "$SRC" "$OUT" <<'EOF'
import sys
src, out = sys.argv[1], sys.argv[2]
html = open(src).read()
anchor = '<script src="board-shim.js"></script>'
assert anchor in html, 'board.html changed: shim tag not found'
html = html.replace(anchor, '<script src="_fixtures.js"></script>\n  ' + anchor, 1)
open(out, 'w').write(html)
EOF

echo "built: $OUT + $FIX"
echo "serve: (cd frontend && python3 -m http.server 8899)"
echo "open:  http://localhost:8899/_harness.html?view=gamestats"
echo "REMEMBER: rm frontend/_harness.html frontend/_fixtures.js before building the app."
