#!/usr/bin/env python3
"""Snapshot the struct type catalogue the simulator plays with.

Two sources, the same two the spectator merges (src-tauri/src/mcp/spectator.rs):

  * MECHANICS from the chain's LCD (`/structs/struct_type`). Never from
    structsd's genesis file: the v0.21 upgrade rewrote the types, and genesis
    no longer describes the live game (the Battleship's secondary weapon and
    Signal Jamming exist only on chain).
  * COPY (weapon names, cheatsheet text) from production structs-pg. The Guild
    API serves it only to a signed-in session, so the migrations that write
    `structs.struct_type_cs` are replayed here, in sqitch.plan order.

Usage: python3 scripts/sync-simulator-types.py [LCD_URL]
"""
import json, pathlib, re, sqlite3, sys, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
PG = ROOT.parent / 'structs-pg'
LCD = (sys.argv[1] if len(sys.argv) > 1 else 'https://public.testnet.structs.network').rstrip('/')


def get(path):
    with urllib.request.urlopen(LCD + path, timeout=30) as r:
        return json.load(r)


def chain_types():
    body = get('/structs/struct_type?pagination.limit=1000')
    rows = body.get('StructType') or []
    height = get('/cosmos/base/tendermint/v1beta1/blocks/latest')['block']['header']['height']
    out = []
    for row in rows:
        t = {}
        for key, value in row.items():
            # uint64 arrives as a decimal string; everything else is a bool or
            # an enum name and is kept verbatim.
            t[key] = int(value) if isinstance(value, str) and re.fullmatch(r'\d+', value) else value
        out.append(t)
    out.sort(key=lambda t: t['id'])
    return out, int(height)


def cheatsheet_copy():
    """Replay every statement that writes struct_type_cs, oldest migration first."""
    plan = [line.split()[0] for line in (PG / 'sqitch.plan').read_text().splitlines()
            if line and not line.startswith(('%', '#', '@')) and line.split()]
    db = sqlite3.connect(':memory:')
    # Statements whose TARGET is struct_type_cs. The trigger migration (a
    # plpgsql body) and the `UPDATE structs.struct_type … FROM struct_type_cs`
    # copies into the main table only read it, so they never match.
    target = re.compile(r'(?i)^(CREATE TABLE|DROP TABLE|INSERT INTO|TRUNCATE TABLE|UPDATE) structs\.struct_type_cs\b')
    for name in plan:
        path = PG / 'deploy' / (name + '.sql')
        if not path.exists() or name.startswith('trigger-'):
            continue
        sql = re.sub(r'--[^\n]*', '', path.read_text())
        for stmt in sql.split(';'):
            s = ' '.join(stmt.split())
            if not target.match(s):
                continue
            s = s.replace('structs.struct_type_cs', 'struct_type_cs')
            s = re.sub(r'(?i)^TRUNCATE TABLE', 'DELETE FROM', s)
            s = re.sub(r'(?i)^DROP TABLE', 'DROP TABLE IF EXISTS', s)
            s = re.sub(r'(?i)CHARACTER VARYING', 'TEXT', s)
            db.execute(s)
    cols = [c[1] for c in db.execute('PRAGMA table_info(struct_type_cs)')]
    return {r[0]: dict(zip(cols, r)) for r in db.execute("SELECT * FROM struct_type_cs WHERE language = 'EN'")}


types, height = chain_types()
copy = cheatsheet_copy()
for t in types:
    cs = copy.get(t.get('class') or t.get('type')) or {}
    for key in ('primary_weapon_label', 'primary_weapon_description', 'secondary_weapon_label',
                'drive_label', 'drive_description', 'passive_weaponry_label', 'passive_weaponry_description',
                'unit_defenses_label', 'unit_defenses_description', 'unit_description'):
        if cs.get(key):
            t[key] = cs[key]

out = ROOT / 'frontend/simulator-types.js'
out.write_text(
    '// Generated by scripts/sync-simulator-types.py — chain ' + LCD + ' at height ' + str(height)
    + ', copy from structs-pg struct_type_cs. Do not edit.\n'
    + 'window.SimulatorTypes = ' + json.dumps({'lcd': LCD, 'height': height, 'types': types}, indent=1) + ';\n')
print('Snapshotted', len(types), 'struct types at height', height, '(' + str(len(copy)) + ' copy rows)')
